POSSIBLE_FIELD_NAMES = {
    "first_name": ["first_name", "firstname", "fname", "name_first", "sei", "yourname"],
    "last_name": ["last_name", "lastname", "lname", "name_last", "mei"],
    "first_name_kana": ["first_name_kana", "firstname_kana", "seikana", "sei_kana"],
    "last_name_kana": ["last_name_kana", "lastname_kana", "meikana", "mei_kana"],
    "name": ["name", "onamae", "namae"],
    "kana": ["furigana", "hurigana", "kana"],
    "company_name": ["company", "company_name", "organization", "firm_name", "kaisha"],
    "department_name": ["department", "department_name", "div", "section", "busho"],
    "email_address": [
        "email",
        "email_address",
        "mail",
        "e-mail",
        "user_email",
        "your_email",
    ],
    "email_address_confirm": [
        "email_confirm",
        "emailconfirm",
        "mail_confirm",
        "email_address_confirm",
        "confirm_email",
        "email2",
        "email_again",
        "mail_con",
    ],
    "phone_number": [
        "phone",
        "phone_number",
        "tel",
        "telephone",
        "mobile",
        "contact_phone",
    ],
    "message_content": [
        "message",
        "content",
        "msg",
        "your_message",
        "comments",
        "body",
        "inquiry",
        "shokai_naiyo",
    ],
    "subject": ["subject", "inquiry_subject", "title", "件名", "topic", "detail"],
    "age": ["age", "your_age", "nenrei"],
    "gender": ["gender", "sex", "your_gender", "seibetsu"],
    # Postal Code variations
    "postal_code": [
        "zip",
        "zip_code",
        "postcode",
        "postal_code",
        "yubin_bango",
        "郵便番号",
    ],
    # Address variations (regular and kana)
    "address_prefecture": [
        "pref",
        "prefecture",
        "address_pref",
        "都道府県",
        "ken",
        "state",
    ],
    "address_city": [
        "city",
        "address_city",
        "shikuchoson",
        "市区町村",
        "ward",
        "ku",
        "gun",
    ],
    "address_street": [
        "address",
        "street",
        "address_street",
        "chome_banchi",
        "番地",
        "住所",
    ],
    "address_building": [
        "building",
        "apartment",
        "mansion",
        "building_name",
        "room_no",
        "建物名",
    ],
    # Address Kana variations (typically takes 'kana' or 'furigana' or 'yomi')
    "address_prefecture_kana": [
        "pref_kana",
        "prefecture_kana",
        "pref_yomi",
        "都道府県カナ",
        "todofuken_kana",
    ],
    "address_city_kana": [
        "city_kana",
        "address_city_kana",
        "shikuchoson_kana",
        "市区町村カナ",
        "shikuchoson_yomi",
    ],
    "address_street_kana": [
        "address_kana",
        "street_kana",
        "chome_banchi_kana",
        "住所カナ",
        "yomi_address",
    ],
    # You might want to add building_kana if that's ever a separate field
}
